routes/web.php
<?php
Route::get('test', 'Controller@test')->name('test');

Route::get('question/{id}', 'QuestionController@view')->name('question.item');
Route::post('question/timeout', 'QuestionController@timeOut')->name('question.timeout');
Route::get('tickets', 'QuestionController@tickets')->name('tickets');
Route::get('tickets/{id}', 'QuestionController@ticket')->name('tickets.question');
Route::get('examination/', 'QuestionController@exam')->name('examination');
Route::get('errors', 'QuestionController@errorsPage')->name('errors.page');
Route::get('top100hardest', 'QuestionController@top100')->name('top100');
Route::post('getErrors', 'QuestionController@getErrors')->name('errors.get');
Route::get('rules/{n?}', 'ReferenceController@rules')->name('rules');
Route::get('rule/{n}', 'ReferenceController@rule')->name('rules.item');
Route::get('subject/{id}', 'QuestionController@subject')->name('question.subject');
Route::get('signs/{category_id?}', 'SignController@category')->name('signs');
Route::get('sign/{id}', 'SignController@item')->name('sign.item');

//Route::get('/', 'PageController@index')->name('index');
Route::get('/', 'PageController@index')->name('home');

Route::post('additional', 'QuestionController@requestAdditionalQuestions')->name('question.additional');
Route::post('/stats/save', 'StatController@save')->name('stat.save');
Route::post('answers/{id}', 'AnswerController@checkAnswer')->name('answer.get');
Route::get('/cities/list', 'CityController@getList')->name('city.list');
Route::get('/school/list/{city_id}', 'SchoolController@getList')->name('school.list');

Auth::routes();

Route::group(['middleware' => 'auth', 'prefix' => 'user'], function () {
    Route::get('/', 'UserController@index')->name('user.index');
    Route::get('stat', 'UserController@stat')->name('user.stat');
    Route::get('settings', 'UserController@edit')->name('user.settings');
    Route::get('options', 'UserController@options')->name('user.options');
    Route::post('save', 'UserController@save')->name('user.save');
    Route::post('save_options', 'UserController@saveOptions')->name('user.save_options');

});

Route::group(['middleware' => 'manager', 'prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('tickets', 'AdminController@tickets')->name('admin.tickets');
    Route::get('tickets/{id}/', 'AdminController@ticket')->name('admin.ticket');
    Route::get('questions/{ticket_id?}', 'AdminController@questions')->name('admin.questions');
    Route::get('question/{ticket_id?}/{id?}', 'AdminController@question')->name('admin.question');
    Route::post('question/{ticket_id?}/{id?}', 'AdminController@question')->name('admin.question.post');
    Route::post('changeAnswerOrder', 'AdminController@changeAnswerOrder')->name('admin.question.order');
    Route::post('save_question/{id?}', 'AdminController@saveQuestion')->name('admin.question.save');

    Route::get('reference/{id?}', 'AdminController@reference')->name('admin.reference.item');
    Route::get('references/{id?}', 'AdminController@references')->name('admin.reference.list');
    Route::post('save_reference/{id?}', 'AdminController@saveReference')->name('admin.reference.save');
    Route::get('get_reference', 'AdminController@getReferenceList')->name('admin.reference.json');
    Route::post('get_referenceById', 'AdminController@getReferenceById')->name('admin.reference_by_id.json');

    Route::get('sign/{id?}', 'AdminController@sign')->name('admin.sign.item');
    Route::get('signs/{id?}', 'AdminController@signs')->name('admin.sign.list');
    Route::post('save_sign/{id?}', 'AdminController@saveSign')->name('admin.sign.save');
    Route::get('get_signs_by_query', 'AdminController@getSignsByQuery')->name('admin.sign.query');
    Route::get('get_rules_by_query', 'AdminController@getRulesByQuery')->name('admin.rules.query');

    Route::get('stat/{period?}', 'AdminController@stat')->name('admin.stat.index');
});

Route::group(['middleware' => 'manager'], function() {
    Route::get('/user/edit/{id}', 'UserController@edit')->name('user.edit');
});

Route::group(['middleware' => 'manager', 'prefix' => 'bot'], function() {
    Route::get('/getme', 'TelegramController@getMe')->name('bot.me');
    Route::get('/getupdate', 'TelegramController@getUpdate')->name('bot.update');
    Route::get('/hook/add', 'TelegramController@addHook')->name('bot.hook.add');
    Route::get('/hook/remove', 'TelegramController@removeHook')->name('bot.hook.remove');
    Route::get('/hook/info', 'TelegramController@getWebHookAnswer')->name('bot.hook.info');
});

Route::post('/bot/hook/{token}', 'TelegramController@webHook')->name('bot.hook.post');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * Class Questions
 *
 * @property integer $id
 * @property string $question
 * @property integer $subject_id
 * @property integer $ticket_id
 * @property integer $category_id
 * @property string $image
 * @property integer $n
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $created_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Answer[] $answers
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereQuestion($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereSubjectId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereTicketId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereCategoryId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereImage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereN($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Question whereCreatedAt($value)
 * @mixin \Eloquent
 */
class Question extends Model
{
    protected $fillable = ['id', 'question', 'subject_id', 'ticket_id', 'category_id', 'image', 'n'];

    private $stat;
    /**
     * Возвращает ответы вопроса
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function answers()
    {
        return $this->hasMany(Answer::class, 'question_id', 'id')->orderBy('n', 'ASC');
    }

    /**
     * Возвращает изображение первого ответа
     *
     * @return $this
     */
    public function getImage()
    {
        return $this->hasOne(Question::class, 'id', 'id')->whereNot('image', null);
    }

    /**
     * Сеттер аттрибута статистики
     *
     * @param Stat $stat Объект статистики
     *
     * @return void
     */
    public function setStatAttribute($stat)
    {
        $this->attributes['stat'] = $stat;
    }
}

app/Models/Stat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Questions
 *
 * @property integer $id
 * @property integer $user_id
 * @property \App\Models\Ticket $ticket
 * @property integer $mode
 * @property integer $errors
 * @property integer $answers
 * @property string $time
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereTicket($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereMode($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereErrors($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereAnswers($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereTime($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Stat extends Model
{

    /**
     * Количество вопросов в билете
     *
     * @var int
     */
    const QUESTIONS_IN_TICKET = 20;

    const QUESTION_LEVEL = [
        'EMPTY_LEVEL' => 'empty',
        'LOW_LEVEL' => 'low',
        'MEDIUM_LEVEL' => 'medium',
        'HIGH_LEVEL' => 'high',
        'FULL_LEVEL' => 'full'
    ];
    /**
     * Возвращает билет
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function ticket()
    {
        return $this->belongsTo(Ticket::class, 'ticket_id', 'id');
    }

    /**
     * Возвращает аттрибут отношения ошибок к количеству вопросов
     *
     * @return float
     */
    public function getRatioAttribute()
    {
        if ($this->errors !== null) {
            return (self::QUESTIONS_IN_TICKET / ($this->errors + 1));
        }

        return null;
    }

    /**
     * Возвращает атрибут процентного соотношения неправильных ответов к кроличеству ответов
     *
     * @return float
     */
    public function getWrongPercentAttribute()
    {
        if ($this->errors !== null) {
            return (($this->errors / self::QUESTIONS_IN_TICKET) * 100);
        }

        return null;
    }

    /**
     * Возвращает атрибут процентного соотношения правильных ответов к кроличеству ответов
     *
     * @return float
     */
    public function getRightPercentAttribute()
    {
        if ($this->errors !== null) {
            return (((self::QUESTIONS_IN_TICKET - $this->errors) / self::QUESTIONS_IN_TICKET) * 100);
        }

        return null;
    }

    /**
     * Возвращает атрибут количества правильных ответов
     *
     * @return int
     */
    public function getRightAttribute()
    {
        if ($this->errors !== null) {
            return (self::QUESTIONS_IN_TICKET - $this->errors);
        }

        return null;
    }

    /**
     * Возвращает аттрибут уровня знаний
     *
     * @return mixed
     */
    public function getLevelAttribute()
    {
        if ($this->errors !== null) {
            if ($this->errors === 0) {
                return self::QUESTION_LEVEL['FULL_LEVEL'];
            }

            if ($this->errors === 20) {
                return self::QUESTION_LEVEL['EMPTY_LEVEL'];
            }

            if ($this->errors < (self::QUESTIONS_IN_TICKET / 2)) {
                return self::QUESTION_LEVEL['HIGH_LEVEL'];
            }

            if ($this->errors > (self::QUESTIONS_IN_TICKET / 2)) {
                return self::QUESTION_LEVEL['LOW_LEVEL'];
            }

            if ($this->errors === (self::QUESTIONS_IN_TICKET / 2)) {
                return self::QUESTION_LEVEL['MEDIUM_LEVEL'];
            }
        }

        return null;
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\ExamHelper;
use App\Helpers\QuestionHelper;
use App\Helpers\UtilsHelper;
use App\Repositories\IRepository;
use App\Repositories\QuestionRepository;
use App\Repositories\StatRepository;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\View\View;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;


/**
 * Class QuestionContoller
 *
 * @package App\Http\Controllers
 */
class QuestionController extends Controller
{
    /**
     * Количество дополнительных вопросов
     */
    const COUNT_OF_ADDITIONAL_QUESTIONS = 5;

    /**
     * Репозиторий запросов к вопросам
     *
     * @var IRepository
     */
    private $questionRepository;

    /**
     * Репозиторий запросов к стастистике
     *
     * @var IRepository
     */
    private $statRepository;

    /**
     * QuestionContoller constructor
     *
     * @param QuestionRepository $questionRepository Экземпляр репозитория
     * @param StatRepository     $statRepository     Экземпляр репозитория
     */
    public function __construct(QuestionRepository $questionRepository, StatRepository $statRepository)
    {
        $this->statRepository = $statRepository;
        $this->questionRepository = $questionRepository;
    }

    /**
     * Отображает страницу с вопросом
     *
     * @param int $id Идентификаторв вопроса
     *
     * @return view|NotFoundHttpException
     */
    public function view($id)
    {
        $data = [
            'item' => $this->questionRepository->getQuestionById((int)$id)
        ];

        if ($data['item'] === null) {
            return UtilsHelper::err404();
        }

        return view('question.item', $data);
    }

    /**
     * Отображает страницу со списком вопросов по идентификатору билета
     *
     * @param Request $request Запрос
     * @param int     $id      Идентификатор билета
     *
     * @return View|NotFoundHttpException
     */
    public function ticket(Request $request, $id)
    {
        $data['action'] = $request->get('action', '');
        $data['isExam'] = false;
        $key = 'ticket' . $id;
        if (env('CACHE_DRIVER') === 'memcached') {
            $data['items'] = Cache::tags(['tickets'])->rememberForever(
                $key,
                function () use ($id) {
                    return $this->questionRepository->getQuestionsByTicket($id);
                }
            );
        } else {
            $data['items'] = $this->questionRepository->getQuestionsByTicket($id);
        }

        if (count($data['items']) === 0) {
            return UtilsHelper::err404();
        }

        return view('question.list', $data);
    }

    /**
     * Возвращает страницу со списокм билетов
     *
     * @return View
     */
    public function tickets()
    {
        $data['title'] = 'Список билетов';
        $items = Cache::tags(['tickets'])->rememberForever('allTickets', function () {
            return $this->questionRepository->getTickets();
        });

        $data['items'] = QuestionHelper::getStat($items, $this->statRepository);

        return view('question.tickets', $data);
    }

    /**
     * Возвращает страницу экзамена
     *
     * @param Request $request Запрос
     *
     * @return View
     */
    public function exam(Request $request)
    {
        $helper = new ExamHelper();
        $helper->setRepository($this->questionRepository);

        $data['action'] = $request->get('action', '');
        $data['items'] = $helper->prepareData();
        $data['isExam'] = true;

        return view('question.list', $data);
    }

    /**
     * Возвращает страницу с ошибками
     *
     * @param Request $request Запрос
     *
     * @return View
     */
    public function errorsPage(Request $request)
    {
        $data['isExam'] = false;

        return view('question.list', $data);
    }

    /**
     * Возвращает вопросы
     *
     * @param Request $request Запрос
     *
     * @return mixed
     */
    public function getErrors(Request $request)
    {
        $ids = $request->get('ids', []);

        return $this->questionRepository->getQuestionsByIds($ids);
    }

    /**
     * Возвращает страницу с топ 100 вопросов
     *
     * @param Request $request Запрос
     *
     * @return View
     */
    public function top100(Request $request)
    {
        $data['action'] = $request->get('action', '');
        $data['items'] = $this->questionRepository->getTop100Hardest();
        $data['top100'] = false;

        return view('question.list', $data);
    }

    /**
     * Возвращает дополнительные вопросы к экзамену
     *
     * @param Request $request Запрос
     *
     * @return view|NotFoundHttpException
     */
    public function requestAdditionalQuestions(Request $request)
    {
        if ($request->list === null) {
            return UtilsHelper::err404();
        }

        $question = $request->question;
        $except = array_filter($request->list);
        $hash = implode($except) . implode($question);

        $data = Cache::tags(['tickets'])->rememberForever(
            'additional_' . $hash,
            function () use ($question, $except) {
                return $this->questionRepository->getAdditionalQuestionsForExam($except, $question, self::COUNT_OF_ADDITIONAL_QUESTIONS);
            }
        );

        return $data;
    }

    /**
     * Отображает страницу со списокм вопросов по теме
     *
     * @param int $id Идентификатор темы
     *
     * @return View
     */
    public function subject($id)
    {
        $key = 'subject' . $id;
        $data['items'] = Cache::tags(['subjects'])->rememberForever(
            $key,
            function () use ($id) {
                return $this->questionRepository->getQuestionsBySubject($id);
            }
        );

        return view('question.list', $data);
    }

    /**
     * Отображает страницу со списков вопросов по актуальности
     *
     * @param string $date Дата
     *
     * @return View
     */
    public function date($date)
    {
        $data = [
            'items' => $this->questionRepository->getQuestionByDate($date),
        ];

        return view('question.list', $data);
    }


    /**
     * Возвращает результат при истекшем времени на выполнение задания
     *
     * @param Request $request Запрос
     *
     * @return JsonResponse
     * @throws \Throwable
     */
    public function timeOut(Request $request)
    {
        $data = [
            'rand' => mt_rand(1, 9999)
        ];

        return response()->json([
            'template' => view('modals._timeout', $data)->render(),
            'data' => $data,
        ]);
    }
}

resources/views/question/item.blade.php
@extends('layouts.app')
@section('content')
    @if($item)
        <h1>{{$item->question}}</h1>
        @if($item->image)
            {{$item->image}}
        @endif
        <hr/>
        <ul class="answers__block">
        @foreach($item->answers as $answer)
            <li><label><input type="radio" name="answer"/> {{$answer->answer}}</label></li>
        @endforeach
        </ul>
    @endif
@endsection

resources/views/question/list.blade.php
@extends('layouts.app')
@section('content')
    @if(isset($items) && count($items) > 0)
        <input type="hidden" id="action" value="{{$action}}"/>
        <div class="ui segment">
            <div class="row question__pagination-wrapper">
                @foreach($items as $i => $item)
                    @if ($item->n % 5 === 1)
                    @if ($item->n !== 1) </div>@endif
                <div class="question__pagination ui buttons ">
                    @endif
                    <a name="page_{{$i+1}}"
                       data-id="{{$item->id}}"
                       data-ticket-id="{{$item->ticket_id}}"
                       data-order="{{($i+1)}}"
                       data-block="{{$item->block_id}}"
                       id="page_{{($i+1)}}"
                       class="ui button notAnswered paginate__item @if ($loop->first) active @endif">{{$i+1}}</a>
                @endforeach
                </div>
            </div>
        </div>
        <div class="ui row">
            <div class="ui two column grid">
                <div class="column question__navigation-wrapper">
                    <div class="ui buttons width mini question__navigation">
                        <a id="page_prev" data-type="next" class="ui button mini">
                            <div class="content">
                                <i class="arrow left icon"></i>
                            </div>
                        </a>
                        @if (isset($isExam) && $isExam === false)
                        <a href="?action=restart" id="restart_ticket" data-type="restart" class="ticket__nav-restart ui button mini">
                            <div class="content">
                                <i class="refresh icon"></i>
                            </div>
                        </a>
                        @endif
                        <a id="page_next" data-type="prev" class="ui mini button">
                            <div class="content">
                                <i class="arrow right icon"></i>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="column question__label-wrapper">
                    <div class="">Билет №<span id="ticket_id">{{$item->ticket_id}}</span>, Вопрос №<span id="question_id"></span></div>
                </div>
            </div>
        </div>
        <div class="question__items ui stacked segment" id="questions">
            <a class="ui teal right  label question__timer">00:00</a>
        @foreach($items as $i => $item)
            <div class="question__item @if ($loop->first) active @endif"
                 data-order="{{($i+1)}}"
                 data-id="{{$item->id}}"
                 data-subject_id="{{$item->subject_id}}"
                 data-category_id="{{$item->category_id}}"
                 data-ticket_id="{{$item->ticket_id}}"
                 data-block_id="{{$item->block_id}}"
                 data-n="{{$item->n}}"
                 id="question_{{($i+1)}}">
                <h2>{{$item->question}}</h2>
                <div class="ui divider"></div>
                @if($item->image)
                    <div class="segment question__image">
                        <img src="{{getenv('APP_URL')}}/images/questions/{{$item->image}}"/>
                    </div>
                @else
                    <div class="question__image question__noimage segment">Вопрос без изображения</div>
                @endif
                <div class="ui middle aligned divided selection list answers__block notAnswered" id="answerList_{{$item->id}}">
                    @foreach($item->answers as $key => $answer)
                        <label
                                class="item answer__item attached segment ui answer_{{($key+1)}}"
                                data-id="{{$answer->id}}"
                                data-question-id="{{$item->n}}"
                                data-answer-num="{{($key+1)}}"
                                id="answer_{{$answer->id}}"
                        >
                            <div class="right floated content">
                                <div class="ui vertical  button primary" tabindex="0">
                                    <div class="content">
                                        <i class="checkmark icon"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="header">
                                <p class="content"><a class="ui blue circular label">{{($key+1)}}</a> {{$answer->answer}}</p>
                            </div>
                        </label>
                    @endforeach
                </div>
            </div>
        @endforeach
        </div>

    @else
        <input type="hidden" id="action" value=""/>
        <div class="ui segment">
            <div class="row question__pagination-wrapper">
                <div class="question__pagination">

                </div>
            </div>
        </div>
        <div class="ui row">
            <div class="ui two column grid">
                <div class="column question__navigation-wrapper">
                    <div class="ui buttons width mini question__navigation">
                        <a id="page_prev" data-type="next" class="ui button mini">
                            <div class="content">
                                <i class="arrow left icon"></i>
                            </div>
                        </a>
                        <a id="page_next" data-type="prev" class="ui mini button">
                            <div class="content">
                                <i class="arrow right icon"></i>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="column question__label-wrapper">
                    <div class="">Билет №<span id="ticket_id"></span>, Вопрос №<span id="question_id"></span></div>
                </div>
            </div>
        </div>
        <div class="question__items ui stacked segment" id="questions">

        </div>
    @endif
    <div class="keys__legend">

    </div>
@endsection

resources/views/question/tickets.blade.php
@extends('layouts.app')
@section('content')
    <h1>{{$title}}</h1>
    <div class="ui cards stackable three">
    @foreach($items as $k => $ticket)
            <a href="/tickets/{{$ticket->ticket_id}}" class="ui card ticket__item" id="ticket_{{$k}}">
                <div class="ticket__item-content" style="background-image: url({{getenv('APP_URL')}}/images/questions/{{$ticket->image}});">
                    <div class="ticket__item-header"><span class="ui blue circular huge label">{{$ticket->ticket_id}}</span></div>
                </div>
                <div class="extra content" id="bar_{{$k}}">
                    @if (isset($ticket->stat->errors))
                        <div class="bar"><div class="bar__level bar__level-right" style="width: {{$ticket->stat->getRightPercentAttribute()}}%">{{$ticket->stat->getRightAttribute()}}</div><div class="bar__level bar__level-wrong" style="width: {{$ticket->stat->getWrongPercentAttribute()}}%">{{$ticket->stat->errors}}</div></div>
                    @endif
                    <span class="left floated">
                        @if (isset($ticket->stat->level))
                            <i class="battery {{$ticket->stat->level}} icon"></i>
                        @endif
                    </span>
                    <span class="right floated error">
                        <span class="ticket__item-progress" id="progress_{{($k)}}">Прогресс <span>0</span>/20</span>
                        @if (Auth::check() === false)
                            <i class="icon warning circle" title="Вы не авторизованы. Ваш прогресс не сохранится по завершению билета."></i>
                        @endif
                    </span>
                </div>
            </a>
        @endforeach
    </div>
@endsection