routes/web.php
<?php
Route::get('test', 'Controller@test')->name('test');

Route::get('question/{id}', 'QuestionController@view')->name('question.item');
Route::post('question/timeout', 'QuestionController@timeOut')->name('question.timeout');
Route::get('tickets', 'QuestionController@tickets')->name('tickets');
Route::get('tickets/{id}', 'QuestionController@ticket')->name('tickets.question');
Route::get('examination/', 'QuestionController@exam')->name('examination');
Route::get('errors', 'QuestionController@errorsPage')->name('errors.page');
Route::get('top100hardest', 'QuestionController@top100')->name('top100');
Route::post('getErrors', 'QuestionController@getErrors')->name('errors.get');
Route::get('rules/{n?}', 'ReferenceController@rules')->name('rules');
Route::get('rule/{n}', 'ReferenceController@rule')->name('rules.item');
Route::get('subject/{id}', 'QuestionController@subject')->name('question.subject');
Route::get('signs/{category_id?}', 'SignController@category')->name('signs');
Route::get('sign/{id}', 'SignController@item')->name('sign.item');

//Route::get('/', 'PageController@index')->name('index');
Route::get('/', 'PageController@index')->name('home');

Route::post('additional', 'QuestionController@requestAdditionalQuestions')->name('question.additional');
Route::post('/stats/save', 'StatController@save')->name('stat.save');
Route::post('answers/{id}', 'AnswerController@checkAnswer')->name('answer.get');
Route::get('/cities/list', 'CityController@getList')->name('city.list');
Route::get('/school/list/{city_id}', 'SchoolController@getList')->name('school.list');

Auth::routes();

Route::group(['middleware' => 'auth', 'prefix' => 'user'], function () {
    Route::get('/', 'UserController@index')->name('user.index');
    Route::get('stat', 'UserController@stat')->name('user.stat');
    Route::get('settings', 'UserController@edit')->name('user.settings');
    Route::get('options', 'UserController@options')->name('user.options');
    Route::post('save', 'UserController@save')->name('user.save');
    Route::post('save_options', 'UserController@saveOptions')->name('user.save_options');

});

Route::group(['middleware' => 'manager', 'prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('tickets', 'AdminController@tickets')->name('admin.tickets');
    Route::get('tickets/{id}/', 'AdminController@ticket')->name('admin.ticket');
    Route::get('questions/{ticket_id?}', 'AdminController@questions')->name('admin.questions');
    Route::get('question/{ticket_id?}/{id?}', 'AdminController@question')->name('admin.question');
    Route::post('question/{ticket_id?}/{id?}', 'AdminController@question')->name('admin.question.post');
    Route::post('changeAnswerOrder', 'AdminController@changeAnswerOrder')->name('admin.question.order');
    Route::post('save_question/{id?}', 'AdminController@saveQuestion')->name('admin.question.save');

    Route::get('reference/{id?}', 'AdminController@reference')->name('admin.reference.item');
    Route::get('references/{id?}', 'AdminController@references')->name('admin.reference.list');
    Route::post('save_reference/{id?}', 'AdminController@saveReference')->name('admin.reference.save');
    Route::get('get_reference', 'AdminController@getReferenceList')->name('admin.reference.json');
    Route::post('get_referenceById', 'AdminController@getReferenceById')->name('admin.reference_by_id.json');

    Route::get('sign/{id?}', 'AdminController@sign')->name('admin.sign.item');
    Route::get('signs/{id?}', 'AdminController@signs')->name('admin.sign.list');
    Route::post('save_sign/{id?}', 'AdminController@saveSign')->name('admin.sign.save');
    Route::get('get_signs_by_query', 'AdminController@getSignsByQuery')->name('admin.sign.query');
    Route::get('get_rules_by_query', 'AdminController@getRulesByQuery')->name('admin.rules.query');

    Route::get('stat/{period?}', 'AdminController@stat')->name('admin.stat.index');
});

Route::group(['middleware' => 'manager'], function() {
    Route::get('/user/edit/{id}', 'UserController@edit')->name('user.edit');
});

Route::group(['middleware' => 'manager', 'prefix' => 'bot'], function() {
    Route::get('/getme', 'TelegramController@getMe')->name('bot.me');
    Route::get('/getupdate', 'TelegramController@getUpdate')->name('bot.update');
    Route::get('/hook/add', 'TelegramController@addHook')->name('bot.hook.add');
    Route::get('/hook/remove', 'TelegramController@removeHook')->name('bot.hook.remove');
    Route::get('/hook/info', 'TelegramController@getWebHookAnswer')->name('bot.hook.info');
});

Route::post('/bot/hook/{token}', 'TelegramController@webHook')->name('bot.hook.post');

app/Models/Stat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Questions
 *
 * @property integer $id
 * @property integer $user_id
 * @property \App\Models\Ticket $ticket
 * @property integer $mode
 * @property integer $errors
 * @property integer $answers
 * @property string $time
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereTicket($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereMode($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereErrors($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereAnswers($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereTime($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Stat whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Stat extends Model
{

    /**
     * Количество вопросов в билете
     *
     * @var int
     */
    const QUESTIONS_IN_TICKET = 20;

    const QUESTION_LEVEL = [
        'EMPTY_LEVEL' => 'empty',
        'LOW_LEVEL' => 'low',
        'MEDIUM_LEVEL' => 'medium',
        'HIGH_LEVEL' => 'high',
        'FULL_LEVEL' => 'full'
    ];
    /**
     * Возвращает билет
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function ticket()
    {
        return $this->belongsTo(Ticket::class, 'ticket_id', 'id');
    }

    /**
     * Возвращает аттрибут отношения ошибок к количеству вопросов
     *
     * @return float
     */
    public function getRatioAttribute()
    {
        if ($this->errors !== null) {
            return (self::QUESTIONS_IN_TICKET / ($this->errors + 1));
        }

        return null;
    }

    /**
     * Возвращает атрибут процентного соотношения неправильных ответов к кроличеству ответов
     *
     * @return float
     */
    public function getWrongPercentAttribute()
    {
        if ($this->errors !== null) {
            return (($this->errors / self::QUESTIONS_IN_TICKET) * 100);
        }

        return null;
    }

    /**
     * Возвращает атрибут процентного соотношения правильных ответов к кроличеству ответов
     *
     * @return float
     */
    public function getRightPercentAttribute()
    {
        if ($this->errors !== null) {
            return (((self::QUESTIONS_IN_TICKET - $this->errors) / self::QUESTIONS_IN_TICKET) * 100);
        }

        return null;
    }

    /**
     * Возвращает атрибут количества правильных ответов
     *
     * @return int
     */
    public function getRightAttribute()
    {
        if ($this->errors !== null) {
            return (self::QUESTIONS_IN_TICKET - $this->errors);
        }

        return null;
    }

    /**
     * Возвращает аттрибут уровня знаний
     *
     * @return mixed
     */
    public function getLevelAttribute()
    {
        if ($this->errors !== null) {
            if ($this->errors === 0) {
                return self::QUESTION_LEVEL['FULL_LEVEL'];
            }

            if ($this->errors === 20) {
                return self::QUESTION_LEVEL['EMPTY_LEVEL'];
            }

            if ($this->errors < (self::QUESTIONS_IN_TICKET / 2)) {
                return self::QUESTION_LEVEL['HIGH_LEVEL'];
            }

            if ($this->errors > (self::QUESTIONS_IN_TICKET / 2)) {
                return self::QUESTION_LEVEL['LOW_LEVEL'];
            }

            if ($this->errors === (self::QUESTIONS_IN_TICKET / 2)) {
                return self::QUESTION_LEVEL['MEDIUM_LEVEL'];
            }
        }

        return null;
    }
}

resources/views/admin/_blocks/_question.blade.php
<div class="field{{ $errors->has('text') ? ' has-error' : '' }}">
    <label class="">{!! Form::label('Текст') !!}</label>
    <div class="">
        {!! Form::textarea('question',null,['class'=>'ui', 'type']) !!}
    </div>
</div>
<div class="field">
    <label>{!! Form::label('Изобаржение вопроса') !!}</label>
    <div>
        @if ($item->image)
            <img src="/images/{!! $item->image !!}"/>
        @endif
        {!! Form::file('image', []) !!}
    </div>
</div>

<div class="four fields">
    <div class="field{{ $errors->has('ticket_id') ? ' has-error' : '' }}">
        <label class="">{!! Form::label('Билет') !!}</label>
        <div class="">
            {!! Form::select('ticket_id',$tickets_list, $item->ticket_id ?: $preset['ticket_id'] ,['class'=>'ui dropdown fluid']) !!}
        </div>
    </div>

    <div class="field{{ $errors->has('category_id') ? ' has-error' : '' }}">
        <label class="">{!! Form::label('Категория') !!}</label>
        <div class="">
            {!! Form::select('category_id',$categories, null,['class'=>'ui dropdown fluid']) !!}
        </div>
    </div>

    <div class="field{{ $errors->has('category_id') ? ' has-error' : '' }}">
        <label class="">{!! Form::label('Тема') !!}</label>
        <div class="">
            {!! Form::select('subject_id', $subjects, null,['class'=>'ui dropdown fluid']) !!}
        </div>
    </div>

    <div class="field{{ $errors->has('n') ? ' has-error' : '' }}">
        <label class="">{!! Form::label('Номер') !!}</label>
        <div class="">
            {!! Form::number('n', $item->n ?: $preset['last_item'], ['class'=>'ui']) !!}
        </div>
    </div>
</div>

@if($item->has('withHint'))
    @foreach($item->withHint as $hint)
    <div class="fields">
        <div class="fourteen field wide ui search">
            <div class="ui left icon fluid input">
                {!! Form::text('reference[text]', $hint->text ?: null, ['class'=>'prompt fluid']) !!}
                <i class="search icon"></i>
            </div>
        </div>
        <div class="two wide field reference_id">
            {!! Form::text('reference[id]', $hint->id ?: null) !!}
        </div>
    </div>
    @endforeach
@else
    add a hint
@endif
<div class=" admin__question_answers">
    @if(count($item->answers) > 0)
        <div class="ui divider"></div>
        @foreach($item->answers as $k => $answer)
        <label data-id="{{$answer->id}}" class=" fields answer__item @if((bool)$answer->right === true) answer__item-active @endif" for="answer_{{$k}}">
            <div class="ui container" style="position:relative;">
                <i class="icon close deleteAnswer" style="position:absolute; top:-3px;right: 0px;"></i>
                {!! Form::checkbox('answers[' . $k . '][right]', 'right', (bool)$answer->right, ['id' => 'answer_' . $k, 'style' => 'opacity:0; height:0px; margin:0px;padding:0px;']) !!}
                {!! Form::textarea('answers[' . $k . '][answer] ', $answer->answer, ['class' => 'ui']) !!}
            </div>
        </label>
        <div class="ui divider"></div>
        @endforeach
    @endif
</div>
<div class="container" id="questionPanel">
    <span class="ui left icon button " id="addAnswer">
        <i class="plus icon"></i> Добавить ответ
    </span>
    {!! Form::submit('Сохранить', ['class' => 'ui submit button right floated']) !!}
</div>

resources/views/admin/_blocks/_reference.blade.php
<div class="field{{ $errors->has('text') ? ' has-error' : '' }}">
    <label class="">{!! Form::label('Текст') !!}</label>
    <div class="">
        {!! Form::textarea('text',null,['class'=>'ui', 'type']) !!}
    </div>
</div>

<div class="field{{ $errors->has('parent_id') ? ' has-error' : '' }}">
    <label class="">{!! Form::label('Родительское правило') !!}</label>
    <div class="ui search" id="searchReference">
        <div class="ui left icon fluid input">
            {!! Form::text('parent', isset($item->parent->text) ? $item->parent->text : null,['class'=>'prompt', 'id' => 'searchReferenceInput']) !!}
            <i class="search icon"></i>
        </div>
    </div>
    {!! Form::hidden('parent_id', null, ['id' => 'searchReferenceInputId']) !!}
</div>
<div class="two fields">
    <div class="field{{ $errors->has('n') ? ' has-error' : '' }}">
        <label class="">{!! Form::label('Номер пункта правил') !!}</label>
        <div class="">
            {!! Form::text('n', null, ['class'=>'ui']) !!}
        </div>
    </div>
</div>

<div class="container">
    {!! Form::submit('Сохранить', ['class' => 'ui submit button right floated']) !!}
</div>

resources/views/admin/_blocks/_sign.blade.php
<div class="field{{ $errors->has('title') ? ' has-error' : '' }}">
    <label class="">{!! Form::label('Заголовок') !!}</label>
    <div class="">
        {!! Form::text('title', null, ['class'=>'ui', 'field']) !!}
    </div>
</div>
<div class="field{{ $errors->has('text') ? ' has-error' : '' }}">
    <label class="">{!! Form::label('Текст') !!}</label>
    <div class="">
        {!! Form::textarea('text',null,['class'=>'ui']) !!}
    </div>
</div>
<div class="field">
    <label>{!! Form::label('Изобаржение знака') !!}</label>
    <div>
        @if ($item->image)
            <img src="/images/{!! $item->image !!}"/>
        @endif
        {!! Form::file('image', []) !!}
    </div>
</div>
<div class="field{{ $errors->has('category_id') ? ' has-error' : '' }}">
    <label class="">{!! Form::label('Категория') !!}</label>
    <div class="">
        {!! Form::select('category_id',$category_list, $item->category_id ?: $preset['category_id'] ,['class'=>'ui dropdown fluid']) !!}
    </div>
</div>
<div class="two fields">
    <div class="field{{ $errors->has('n') ? ' has-error' : '' }}">
        <label class="">{!! Form::label('Номер знака') !!}</label>
        <div class="">
            {!! Form::text('n', null, ['class'=>'ui']) !!}
        </div>
    </div>
</div>

<div class="container">
    {!! Form::submit('Сохранить', ['class' => 'ui submit button right floated']) !!}
</div>

resources/views/admin/_blocks/footer.blade.php
<div id="_modals"></div>